# Generated by Django 5.2.8 on 2025-11-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
